#!/usr/bin/env bash

echo "== delete-objects =="

set -e

if [ -z "$1" ]; then
    echo "-- In order to create a bucket need to pass bucket name as param eg. ./create-bucket [my-bucket-name]"
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 --bucket ${BUCKET_NAME} \
    --query Contents[].Key |
    jq -n '{Objects: [inputs | .[] | {Key: .}]}' >/tmp/delete_objects.json

aws s3api delete-objects --bucket ${BUCKET_NAME} --delete file:///tmp/delete_objects.json

#clean the json file
