#!/usr/bin/env bash

echo "== List Objects =="

if [ -z "$1" ]; then
    echo "-- In order to create a bucket need to pass bucket name as param eg. ./create-bucket [my-bucket-name]"
    exit 1
fi

BUCKET_NAME=$1

aws s3api list-objects-v2 \
    --bucket $BUCKET_NAME
